---
title: "GPU computing with R"
author: "Wouter van Amsterdam"
date: 2018-01-15
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

### Setup

```{r}
library(gpuR)
detectGPUs()
```

### Simple benchmark

on CPU

```{r}
dim_pow = 8
n = 10^dim_pow
n_rows = 10^ceiling(dim_pow / 2)
n_cols = 10^floor(dim_pow / 2)

matA = matrix(rnorm(n), nrow = n_rows)
matB = matrix(rnorm(n), nrow = n_rows)

system.time(matA %*% t(matB))
system.time(matA + matB)
```

on GPU with matrix in RAM

```{r}
gpuA = gpuMatrix(rnorm(n), nrow = n_rows, ncol = n_cols, type = "double")
gpuB = gpuMatrix(rnorm(n), nrow = n_rows, ncol = n_cols, type = "double")

system.time(gpuA %*% t(gpuB))
system.time(gpuA + gpuB)
```

on GPU with matrix in GPU-RAM

```{r}
vclA = vclMatrix(rnorm(n), nrow = n_rows, ncol = n_cols, type = "double")
vclB = vclMatrix(rnorm(n), nrow = n_rows, ncol = n_cols, type = "double")

# system.time(vclA %*% t(vclB))
system.time(vclA + vclB)
```



### Simulate data

```{r}
npred = 50
nobs  = 1000
betas = rnorm(npred)
sresid= 0.1

x     = matrix(rnorm(npred * nobs), nrow = nobs)
y     = x %*% betas + rnorm(nobs, sd = sresid)

```



## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
