---
title: "Thoughts and assingments in epidemiology and statistics"
output:
  html_document:
    toc: false
---

This website is made to share the assignments I worked out for 
statistic courses in the Epidemiology Graduate Program of the Julius Center, Utrecht, the Netherlands

# Blog posts

[pre-testing and type-I error rates: re-analysis of Rasch](cs_pre_testing_type_I_error.html)

[the circle dance: strategy for positioning at equidistance in a group](circle_dance.html)

# Worked-out assignments

## Classical Methods in Data Analysis

[assignments week 1](c_assignments_week1.html)

[assignments week 2](c_assignments_week2.html)

[assignments week 3](c_assignments_week3.html)

[case studies (not finished)](c_case_studies.html)

## Modern Methods in Data Analysis

[assignments week 1](mm_assignments_week1.html)

[assignments week 2](mm_assignments_week2.html)

## Computational Statistics

[assignments Advanced R](cs_assignments.html)

[assignments Simulation Studies](cs_assignments_sim.html)

## Advanced methods in causal research

[assignments Advanced methods in causal research](acr_assignments.html)

## Generalized linear models

[assignments](glm_assignments.html)

## Prognostic research

[assignments](pr_assignments.html)

## Mixed models

[assignments](mim_assignments.html)

[presentation](mim_presentation_lc.html)

## Applied Bayesian statistics

[presentation](https://docs.google.com/presentation/d/1-xPRPq_CFF4BsuQpn3yaFx6g3Iz07qfNEPvXSqfVp-E/edit?usp=sharing)

## Missing data

[assignments](md_assignments.html)

# Notes and commmon errors

**working directory**

Due to how this website was made, the R-code 'thinks' it is in the `analysis` 
subdirectory, while the data sits in the `data` directory, which is found from 
the parent directory. Working with Rmarkdown and keeping track of the 
directory is not too easy at all. After modern methods, I switched to using
the package `here`, which is specifically designed to target such problems.

Before that I used the function `fromParentDir`, which allows you to call files from 
the parent directory. The function can be found in the package `epistats`, 
which can be installed with `devtools::install_github("vanAmsterdam/epistats")`

If `devtools` is not yet installed, first run `install.packages("devtools")`


**packages and functions**

Sometimes different packages provide functions with the same names. 
To make sure you use the intended function 
(and to circumvent using `library(package)`), use `<package>::<function>` 
to use `<function>` from package `<package>`, like `epistats::fromParentdir`
